### ISSUE TITLE
Sink exception

### ISSUE THREAD

**Issue by clauderobi** [KjellKod/g3sinks#114]
I am trying to understand what happens when a sink can not complete its task (ie can addEntry can not complete). I see that there is no error handling in the sinks provided here (and directly in g3log) so I looked for try-catch, which I found in SinkHandle::call but from there up I got lost....

Instead of digging more and understand what happens I decide to ask my question here since I presume that others may be interested in the answer, so, what happens when an exception occurs? Is the log entry lost or stored somewhere? My main concern is that the file system I send the filesink may not be ready immediately as the program starts; but I do not want to loose log entries. And I also do not want my program to wait until the filesystem is ready...

**Comment by KjellKod** [comment]
The sinks should preferably be added at earls startup to avoid entry loss but they can be added whenever. 

The sinks receive the log entries over a queue. If a sink is blocking or being slow in processing a log message then it will take longer time before the next message is processed. There is strict FIFO ordering. 

Error handling must be done within the sink. If the custom sink may throw then the error handling for that should be done within the sink and not impact on the calling code. 

If exceptions are not handled they will impact on the system just like any unhandled C++ exception - for async call with returned futures I believe the exception would be within the future. For async calls with no future return value I believe this would trigger a runtime fatal exception and kill the process

**Comment by KjellKod** [comment]
Also, I’m not sure what file system you would be working on that “is not ready” to receive write requests. No file system that I’ve heard about — unless the file system is corrupted and then no waiting will help

**Comment by clauderobi** [comment]
The file system is simply not yet mounted. My app is started my systemctl and yes I could make sure that it is started after all auto mount are completed but I have other reasons for my app to start as early as possible.

**Comment by KjellKod** [comment]
If you want to make sure that you don’t loose any messages -  I think what you need is a custom sink that is either 
A) blocking on the first received log message, until it can see that the file system is ready 
B) receives and  buffers internally in the sink until it can see that the file system is ready

I’d recommend going with the default sink or the log rotating one in g3sinks and either wrap it or add your own customizations

one benefit with wrapping it is that if there are community changes to it you don’t have to worry about merge concerns since your own wrapper code is simply using the G3log or g3sinks repo sink
