### ISSUE TITLE
std::remove should instead be using std::filesystem

### ISSUE THREAD

**Issue by KjellKod** [KjellKod/g3sinks#38]
Also, it **must** handle and deal with permission issues. Currently the LogRotate will silently fail if it cannot delete a file due to permission issues. Next time around it will potentially try to delete the same file again and fail. 

--> Expected behavior should instead be to scream bloody murder if it cannot be deleted. 
--> A potential change could also be that it tries to delete the next file in order but I'm not sure about that yet.

**Comment by KjellKod** [comment]
On a linux system you can trigger this by using the `chattr` command. 
Example:
` sudo chattr +i myexample.log.2017-01-25-13-16-25.gz` 
This would then not be deleted, the std::remove of the oldest file would fail but a new tgz file would instead be created. 

The functions that might be involved here are:
1. `expireArchives( ... )`: https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/LogRotateUtility.cpp

2. `rotateLog( ... )`: https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/LogRotateHelper.ipp

Suggestions on expected behavior? Feedback is welcome. At this point I am considering any of these options: 

1. **[Kjell's suggestion]** try to delete the oldest archive before creating a new archive. If the delete fails then also do not create a new archive. The old log will then be lost and the log writing will truncate the log file and just use up that log file again. Apart from this, no changes. 

2. using std::terminate to exit with std:;cerr and log message why

3. delete the next oldest archive instead (and so forth), if none can be delete --> 1?

**Comment by KjellKod** [comment]
blocked on c++17 and std c++17 adoption

**Comment by thomasCresson** [comment]
I'm preparing a pull request on the removal of the boost dependency using std::filesystem instead (do you have an issue associated with it or should I create a new one ?). Now that the required version of the standard has been set to c++17, I think it's time we get rid of this dependency (I'm currently working on the CMakeLists in order to remove the dependencies with boost and .

On the use of std::filesystem::remove, depending on what strategy you have in mind, we can use a throwing version or a non throwing version (the non throwing version populates a std::error_code ([this example](https://en.cppreference.com/w/cpp/filesystem/filesystem_error) is using std::filesystem::copy_file but std::filesystem::remove is working exactly the same way).

For the solutions you are proposing, I think that terminating the program (solution n°2) for a problem with the logging facility is, maybe, a bit too much.

The first solution might be the best to implement at first (TBH I don't have any other good solution in mind for now). If you don't have another solution in mind right now I think I'm gonna start by implementing this one.

**Comment by KjellKod** [comment]
@thomasCresson . I agree that `std::terminate` is a bit harsh.  I leave it up to you whether it should usethe `std::error_code`or not. g3sinks is a mesh of sinks from different folks so there's no need to have throw/no-throw policy uniform across sinks (probably not the best decision but it's what we have)

Please be aware that std::filesystem might not be rolled-out on all platforms yet.  If it isn't rolled out on all platforms (OSX, Windows, Linux) then it might be better to create a new sink rather than changing the existing one.

**Comment by thomasCresson** [comment]
@KjellKod well I'm trying to see whether the `filesystem` library is correctly implemented on MSVC but it seems that there are still quite a lot of bugs that are resolved only on the later versions (and even some that are just planned on future versions). It seems that on Linux (gcc and clang) and on OSX (Apple clang) it is more than mature (it's been at least 2 years that it has been added on Apple clang and at least 3 for clang and gcc).

I'm probably gonna copy the LogRotateSink and name it LogRotateFsSink or something like this (probably better for retro-compatibility you're right).

Should I be aware of anything to change in order to trigger the unit testing on your CI interface (appveyor was it ?) ? I'm not familiar with this tool at all and I don't want to upload a pull request without unit testing ^^"

I would like to upload this pull request in two steps:
1. Just getting rid of the boost dependency
2. try to address all the enhancement that you and others had in mind for using filesystem

Would this suit you ?

**Comment by KjellKod** [comment]
Unfortunately appVeyor is only Windows :( 
So you will at least know if the PR didn't break windows. 

I or someone in the community need to setup CircleCI (not sure if there are other free options) as I have a zero budget for paying for Travis-CI. Until that's done it's manual testing. 

I can help out with verification on OSX and Ubuntu if it's needed.

**Comment by KjellKod** [comment]
for 1. and 2. If you are suggesting to do those in two separate pull requests then I think that's a great approach. KISS, right? 

The AppVeyor (or CircleCI) can be triggered manually but it should trigger for the PR when it get posted and for each commit you do on the PR. 

I think you can do a "draft PR" if you want to keep it "in progress" to see where the CIs are landing.

**Comment by thomasCresson** [comment]
Oh and by the way, do you have any coding style guidelines or format ?

**Comment by KjellKod** [comment]
Coding style isn’t formalized for g3sinks since it’s a community collection of sinks. I’d recommend to keep with the existing style of the sinks your are copying-modifying - However, since you are creating a new sink you can feel free to use other coding styles 

(in general though, space, not tabs, keep it sane, back it ALL up with TDD or at least tests. Well written tests should imho cover 90-95% of the code)

**Comment by KjellKod** [comment]
https://github.com/KjellKod/g3sinks/pull/124 closes this one. @thomasCresson coding config styles added for clang-format and for sublime

**Comment by thomasCresson** [comment]
OK! @KjellKod I understood that you already moved the sink into pure c++17. Should I still consider submitting a pull request?

I have to be honest, I stopped working on it a while ago but was going to go back to it this weekend (I was trying to refractor the whole thing).
