### ISSUE TITLE
handle call() and string lifetime

### ISSUE THREAD

**Issue by JoelStienlet** [KjellKod/g3sinks#75]
Hello,
First of all, many thanks for making this library.
I'd like to discuss a bug I had yesterday, when calling syslog-sink's setIdentity(const char* id). 
I used the call() method of the sink handle, as described in the API documentation. But I got some illegal characters on my terminal (echoToStderr() enabled), and nothing in journald. After some search, I found that the original string's buffer had already been reused by something else at the moment the worker thread executed the setIdentity(const char* id) function.

I did a test adding std::future<void> .get() after the call(), then everything went fine ( because now I waited for the thread to finish the task), but then we loose the speed benefit of performing an asynchronous call, in the worst case we have to wait for the scheduler to schedule the worker thread, then this thread again. 

So I think a better correction would be to change the way strings are passed to these functions.
Instead of:
`void setIdentity(const char* id) { _identity = id; }`
I think it would be better to use:
`void setIdentity(std::string id) { _identity = std::move(id);}`
Now the original string gets copied when performing call(), and the original string can be deleted right after that.

**Comment by KjellKod** [comment]
FYI @michaelbgratton

**Comment by KjellKod** [comment]
@JoelStienlet  Hi Joel
I contacted (above) the author of the sink. 
My two cents 

I see your point with copy being better than a temporary from a string stream. In this specific case yes it would be better to change this. There are a couple of points to keep in mind 

1. The `call` function is to be able to get to custom API within the sink without having to know the details of the sink. It is the responsibility of the sink code (author) and to specify what is safe code calling and what isn’t and for the user of the sink to follow that.  In this case the `setIdentity` - although not documented obviously rely on the temporary `const char*` to stay valid for the duration of the call. 
A) Documentation (or just read the code) should make this clear. 
B) the code can be changed to be as you suggested or another function with a different name `setIdentityWithStr` could be used (yup, not a pretty name choice). 

2. I think it’s assumed overall that frequent and fast calling to the sink should not be done with the `call` function - which is why you get the std::future returned also.  Frequent and fast calling should only be done with the sink’s logging IMO.  The call provides a thread safe means to configure the sink provided the sink API and handling + the client of the sink is handling the calls correctly. 

3. If a sink is called between library runtimes then there could be a problem if dynamic memory allocated in one runtime is destroyed past the library border. This is a big pain depending on what state you are in and for that reason it does make sense to have `setIdentity` as is. I do agree that it needs to be improved with documentation and or supplemented with another function which doesn’t rely on the `const char*`  being kept alive for the remaining call. 

@JoelStienlet I suggest you create a PR with an additional function to complement this sink’s `setIdentity` function. It would be helpful if you also added a comment for both functions about usage

**Comment by JoelStienlet** [comment]
Thank you for the (very) fast reply and clarifications.

1.B) For the name, I suggest appending a short generic suffix like "NoJn" standing for "No thread Join required": `void setIdentityNoJn() `
This will highlight which functions in the sink interfaces are safe to just "call and forget", and by contrast, also highlight which ones may sometimes require a thread join when memory is short lived. This suffix can be standardized accross sinks (`changeLogFile()` in LogRotate may also benefit from a `changeLogFileNoJn()` version for example).

3) Not sure if I fully understand this issue: is it about the ABI compatibility between compilers and compiler versions?

I'll create a PR with a few small changes to add these new functions, and explanatory comments.

**Comment by JoelStienlet** [comment]
for point 2. I would add that the "NoJn" functions also offer minimal worst case latency in the caller thread. 
For example of use case, in a program controlling some sort of machine where "fast" response times are required, it may be desirable to rotate the log file without having to join the worker and wait for the OS to open a file on a remote NFS server.

**Comment by KjellKod** [comment]
Not sure I’m sold on the `NoJn` but I have no better alternative. Please add a comment on it and maybe on the syslog sink’s markup description for clarity. 

This link explains the problem with memory allocation and deallocation across runtimes. It has nothing to do with ABI

https://stackoverflow.com/questions/12215681/issues-when-memory-allocation-deallocation-when-linking-with-static-c-runtime

**Comment by JoelStienlet** [comment]
A satisfactory solution has been found. For reference, see the discussion in PR76.
